
spring:
  datasource:
    #The DB name cannot contains hyphen character "-", you should use underscore character "_".
    url: jdbc:mysql://localhost:3307/outbox_pattern_db?useSSL=false
    username: user
    password: user

    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
    hikari:
      pool-name: outbox_pattern_db

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Avoid accidental performance issue: https://github.com/spring-projects/spring-boot/issues/7107
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      #The platform for DDL or DML scripts (it's all by default)
      platform: mysql

      #Account for running schema scripts
      username: root
      password: root
