package org.tnmk.practicetransactionoutbox.pro00mysqlsimple.samplebusiness.service;

public interface MdcConstants {
  String OUTBOX_CLASS = "outbox_class";
  String OUTBOX_METHOD = "outbox_method";
  /**
   * The outboxId is the unique Id for each outbox event.<p/>
   * Note that this "Id" value is different from "uniqueRequestId":<br/>
   *  - We can decide whether many outbox events are allowed to process the same business action (e.g. "cleanUpUser 1") at the same time or not.
   *    If not, the application can assign a uniqueRequestId for that event so that other events won't process the same uniqueRequestId again.
   *    So, that uniqueRequestId is the Id generated by application.<br/>
   *  - And no matter whether we allow many events to process the same business action or not,
   *    each outbox event itself still have a unique Id generated by the framework. That Id is called `outboxId`.
   */
  String OUTBOX_ID = "outbox_id";
  /**
   * @see #OUTBOX_ID  Please view "OutboxId" for more explanation about the difference.
   */
  String OUTBOX_UNIQUE_REQUEST_ID = "outbox_unique_request_id";
}
