
spring:
  datasource:
    #The DB name cannot contains hyphen character "-", you should use underscore character "_".
    url: jdbc:mysql://localhost:3307/outbox_pattern_db?useSSL=false
    username: user
    password: user

    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
    hikari:
      pool-name: outbox_pattern_db

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate.format_sql: true

      # This config must match with Dialect config in TransactionalOutboxConfig.persistor()
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Avoid accidental performance issue: https://github.com/spring-projects/spring-boot/issues/7107
    open-in-view: false
    hibernate:
      ddl-auto: update
outbox:
  #                    Spring cron expression (which is a bit different from K8s cron expression):
  #                      ┌───────────── second (0-59)
  #                      │    ┌───────────── minute (0 - 59)
  #                      │    │ ┌───────────── hour (0 - 23)
  #                      │    │ │ ┌───────────── day of the month (1 - 31)
  #                      │    │ │ │ ┌───────────── month (1 - 12) (or JAN-DEC)
  #                      │    │ │ │ │ ┌───────────── day of the week (0 - 7)
  #                      │    │ │ │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
  #                      *    * * * * *
  workerCronExpression: "*/15 * * * * *"

